version: '3'

services:
  broker-service:
    image: evgeniy19/broker-service:1.0.0
    ports:
      - "8080:80"
    deploy:
      mode: replicated
      replicas: 1

  listener-service:
    image: evgeniy19/